### ISSUE TITLE
Documentation & metadata

### ISSUE THREAD

**Issue by adamperkowski** [cartercanedy/rawbit#1]
Hello. I'd love to package this for the AUR, but
- [x] there are other projects named rawdog:
https://github.com/chirlu/rawdog
https://github.com/AbanteAI/rawdog
i see the project is still in its early development stage so might be worth renaming before it's too late
- [x] there is no README; would be nice to have a little description and overview of the tool
- [x] more cargo package metadata (like repo, authors, license, etc.) could also be useful
- [x] there are no git tags / releases

and that would be about it. Thanks.

**Comment by adamperkowski** [comment]
Oh and also, master doesn't compile.

**Comment by cartercanedy** [comment]
Just created the readme, cd workflow is a work in progress. Probably going to use a release branch with auto release on tag push

**Comment by adamperkowski** [comment]
> Just created the readme, cd workflow is a work in progress. Probably going to use a release branch with auto release on tag push

Could you also bundle `LICENSE` and `README` files with releases? Not an issue if no, just a QOL improvement.

**Comment by cartercanedy** [comment]
Yeah, I'll take a look

**Comment by adamperkowski** [comment]
Something like `x86_64-unknown-linux-gnu.tar.gz` or `xz` or whatever you like really and include files there.

**Comment by cartercanedy** [comment]
You should be good to go for AUR packaging, lmk if you run into trouble
